import './globals.css';
import { Rethink_Sans } from 'next/font/google';

const rethinkSans = Rethink_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={rethinkSans.className}>{children}</body>
    </html>
  );
}
